### ISSUE TITLE
Installing modules

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/locator#2]
### Goals
Install the axios library which will help us make HTTP request. 

### Tasks
- [x] install axios by typing npm install axios --save
- [x] install eslint version 6.0.0 as dev dependencies
- [x] clone the current project by creating a folder clone_locator, copying the package.json and package-lock.json from the locator project into the  the clone_locator project
- [x] run npm i to install all the dependencies as it is installed in locator.js
- [x] install global module : install hexo-cli
- [x] test the version of hexo installed
